apiVersion: v1
kind: PersistentVolume
metadata:
 name: appsody-manual-pipeline-run-pvc
spec:
 capacity:
   storage: 5Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /var/lib/appsody-manual-pipeline-run-pvc