apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsody-manual-pipeline-run-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
